language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-docpad-plugin' ]; then cd .. && eval "mv $currentfolder generator-docpad-plugin" && cd generator-docpad-plugin; fi

